print("Hello, World!")
print("Hira")
print("Hira Ali")
print("1 2 3")
print("Hello\nWorld")
print("Hello\tWorld")
print("apple,banana,cherry")
print("1-2-3")
print("Hello World")
print("12")
print("He said","Hello!")
print("This is a backslash:\ ")
print("I am 22 years old")
print("The number is 5")
print("1")
print("2")
print("3")
print("4")
print("5")